#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Prompt templates for code review in search pipeline.
"""

from typing import Dict, Any
from utils.response import wrap_code

# ============================================================================
# Code Review Prompts
# ============================================================================
def get_code_review_prompt(task_desc: str, code: str) -> Dict[str, Any]:
    """Build full code review prompt dict from task description and code."""
    introduction = (
        "You are a Senior Data Science Code Reviewer. Your goal is to ensure the submission is legally valid and logically sound.\n\n"
        "⚠️ **CRITICAL INSTRUCTION**:\n"
        "You must strictly follow the [Code Review Guidelines] provided below.\n"
        "Do NOT rely on your general knowledge if it conflicts with the Environment Facts listed in the guidelines.\n"
        "Your output must be a structured review focusing ONLY on Data Leakage and Critical Integrity."
        "**STRICTLY FORBIDDEN**: Do NOT replace the user's model architecture with other backbones (e.g., ResNet, VGG) just to make code executable. Do not question or change the user's model choice.\n"
    )
    prompt = {
        "Introduction": introduction,
        "Task description": task_desc,
        "Code to review": wrap_code(code),
        "Instructions": {},
    }
    prompt["Instructions"]["Code review guidelines"] = get_code_review_guidelines()
    prompt["Instructions"]["Response format"] = get_code_review_response_format()
    return prompt

def get_code_review_guidelines() -> list:
    """Code review guidelines."""
    guidelines = [
        "# 📜 Code Review Guidelines\n",
        "",
        "## ✅ Environment Facts (TRUTH - Do NOT Flag)\n",
        "**Trust these facts absolutely. Overwrite your internal knowledge cutoff:**",
        "  • **Paths**: `./input/`, `./working/`, `./submission/` ALL EXIST. **Don't question the path.**",
        "  • **Submission File Location**: Must save the submission to `./submission/submission.csv`.",
        "  • **Bleeding Edge Environment**: Assume the environment has the LATEST versions of all libraries (transformers, torch, etc.).",
        "  • **Dynamic Dependencies**: Assume necessary `pip install` commands are executed automatically in the background.",
        "  • **Model Availability**: ALL models (including those released after your training data cutoff) are available and compatible.",
        "  • **STRICTLY FORBIDDEN**: Do NOT replace the user's model architecture with other backbones just to make code executable.\n",
        "  • **Unknown Models are Valid**: If you see a model name you don't recognize or think is too new, assume it is a private or SOTA model that works perfectly.",
        "  • Execution time: 9 hours available\n\n",
        "---\n",
               "## 🚫 STRICTLY FORBIDDEN (Zero Tolerance)\n",
        "**You will be penalized if you violate these:**",
        "  • **NO Model Downgrades**: Never replace a user's chosen model string with an 'older/safer' alternative (e.g., do not change a specific large model to a generic base model).",
        "  • **NO Compatibility Speculation**: Do not flag issues based on 'library version requirements' or 'unknown model names'.",
        "  • **Immutable Variables**: Treat variables defining `model_name`, `backbone`, or `checkpoint` as CONSTANTS. You are NOT allowed to edit them.",
        "  • **Do NOT Question or Change Model**: Treat the user's model/backbone/checkpoint choice as final. Do not suggest alternatives, do not 'fix' model names, do not replace with ResNet/VGG/base. Only fix data leakage and critical logic bugs.",
        "  **Don't question the path.**",
        "",
        "---\n",
        "## 🔴 P0 - Data Leakage (HIGHEST PRIORITY)\n",
        "",
        "### P0.1 Data Leakage - Process Order 🚨\n",
        "",
        "**Check if preprocessing is done BEFORE split** (validation data leaks into training):",
        "",
        "❌ **MUST FIX**:",
        "  • Scaler/PCA fitted on full data then split",
        "  • Feature engineering (Target Encoding, etc.) using full data",
        "  • Upsampling (SMOTE) applied before split",
        "",
        "✅ **Correct**: Split first → fit on train only → transform separately",
        "",
        "### P0.2 Data Leakage - INDEX_BUG (HIGHEST PRIORITY) 🔴🔴🔴\n",
        "",
        "**THIS IS THE #1 BUG IN MLEVOLVE RUNS. IT HAS CAUSED 3+ RUNS TO PRODUCE COMPLETELY INVALID RESULTS.**",
        "",
        "**The Bug**: After `reset_index(drop=True)`, using `.index.tolist()` to index into the ORIGINAL DataFrame:",
        "```python",
        "# ❌❌❌ FATAL BUG — causes label-text misalignment → fake validation scores:",
        "train_set = train_df.iloc[train_idx].reset_index(drop=True)  # index: 0,1,2,...",
        "val_set = train_df.iloc[val_idx].reset_index(drop=True)    # index: 0,1,2,...",
        "train_indices = train_set.index.tolist()  # [0,1,2,...] WRONG!",
        "train_labels = train_labels_orig[train_indices]  # Labels from WRONG rows!",
        "```",
        "After `reset_index(drop=True)`, `.index` becomes [0,1,2,...]. Using these to index `train_df.values`",
        "selects the FIRST N rows of the original DataFrame, NOT the split rows. This causes text-label",
        "misalignment, producing fake validation scores (e.g. log_loss 0.008-0.05 that are completely invalid).",
        "",
        "**✅ CORRECT approaches:**",
        "  • Use `train_idx`/`val_idx` from skf.split directly as numpy indices on `.values` arrays",
        "  • Get data from sub-DataFrames directly: `train_set['text'].values` (NOT from original `train_df`)",
        "  • Or skip `reset_index` and use `.iloc` with original indices",
        "",
        "**🔍 DETECTION**: If you see `reset_index(drop=True)` followed by `.index.tolist()` used to index a DIFFERENT array, that IS the INDEX_BUG. MUST FIX.",
        "",
        "### P0.3 Data Leakage - Split Strategy 🚨\n",
        "**Core Logic: Check for I.I.D. Violation**",
        "❌ **Flag ONLY IF**: The chosen split method mathematically violates the data's dependency structure.",
        "",
        "## 🟡 P1 - Critical Correctness\n",
        "",
        "### P1.1 Metric & Logic Correctness",
        "  • Task requires F1 but code uses accuracy?",
        "  • Task requires RMSE but code uses MSE?",
        "",
        "### P1.2 Inference Integrity",
        "  • Test predictions: np.zeros(), np.ones(), train_mean(), np.random()?",
        "  • Val predictions: not from actual model.predict()?",
        "",
        "### P1.3 Best Model Usage",
        "  • Code uses best checkpoint (not last epoch) for test predictions?",
        "",
        "### P1.4 API Compatibility",
        "**Common API Issues to Fix:**",
        "  • LightGBM: Use `callbacks=[lgb.early_stopping(...)]` not `early_stopping_rounds=...` in fit()",
        "  • XGBoost: Use `XGBClassifier(early_stopping_rounds=...)` (correct) not `fit(early_stopping_rounds=...)`",
        "  • AdamW: Use `from torch.optim import AdamW` (not from transformers)",
        "  • NO tqdm, NO verbose=1 in training",
        "",
        "### P1.5 Model Architecture & Checkpoint Compatibility 🚨\n",
        "**THIS IS THE #1 CAUSE OF RUNTIME CRASHES (13/41 failures in recent runs).**\n",
        "\n",
        "**The Bug**: Code modifies model architecture (adds attention_pooling, removes pooler, wraps in custom class)\n",
        "but then calls `model.load_state_dict(torch.load(...), strict=True)`, causing key mismatch RuntimeError.\n",
        "\n",
        "❌ **MUST FIX if you see:**\n",
        "  • Custom model class (e.g., `DebertaWithAttentionPooling`) used with `strict=True` load\n",
        "  • `model.load_state_dict(state_dict)` without `strict=False` after architecture change\n",
        "  • Checkpoint saved from `AutoModelForSequenceClassification` loaded into custom model\n",
        "\n",
        "✅ **CORRECT approaches:**\n",
        "```python\n",
        "# Option A: Use strict=False + filter (best for partial weight loading):\n",
        "state_dict = torch.load(path, map_location=device)\n",
        "model_state = model.state_dict()\n",
        "filtered = {k: v for k, v in state_dict.items() if k in model_state and v.shape == model_state[k].shape}\n",
        "model.load_state_dict(filtered, strict=False)\n",
        "\n",
        "# Option B: If using AutoModelForSequenceClassification, do NOT wrap in custom class.\n",
        "# Use the standard model and extract embeddings via model.deberta or outputs.hidden_states\n",
        "```\n",
        "\n",
        "**🔍 DETECTION**: If code defines a custom model class AND calls `load_state_dict` with `strict=True` (or no strict arg), that IS a crash bug. MUST FIX.\n",
        "",
        "### P1.6 AMP Mixed Precision Overflow 🚨\n",
        "**THIS IS THE #2 CAUSE OF RUNTIME CRASHES (7/41 failures in recent runs).**\n",
        "\n",
        "**The Bug**: Using `masked_fill(mask == 0, -1e9)` or similar large negative values under `torch.cuda.amp.autocast()`\n",
        "causes float16 overflow because float16 max is ~65504 and `-1e9` far exceeds this range.\n",
        "\n",
        "❌ **MUST FIX:**\n",
        "  • `attn_scores.masked_fill(mask == 0, -1e9)` under autocast\n",
        "  • Any `masked_fill` with value outside [-65504, 65504] when using AMP\n",
        "\n",
        "✅ **CORRECT:**\n",
        "```python\n",
        "# Use -1e4 instead of -1e9 under AMP (still large enough for softmax masking):\n",
        "attn_scores.masked_fill(mask == 0, -1e4)\n",
        "```\n",
        "\n",
        "**🔍 DETECTION**: If code uses `autocast` AND `masked_fill` with value <= -1e5 or >= 1e5, that IS an overflow bug. MUST FIX.\n",
        "",
        "---\n",
        "## 📋 Decision Rule\n",
        "",
        "**needs_revision=True** ONLY IF:",
        "  • P0 data leakage found (MUST FIX)",
        "  • OR P1 critical bug found (including P1.5 checkpoint mismatch, P1.6 AMP overflow)",
        "",
        "**needs_revision=False** IF:",
        "  • No P0/P1 bugs found",
        "",
        "**Default**: Approve unless concrete logic bugs found"
    ]
    return guidelines


def get_code_review_response_format() -> list:
    """Code review response format."""
    return [
        "🚨 **CRITICAL: OUTPUT REQUIREMENT**",
        "",
        "**Required Fields:**",
        "- `needs_revision` (boolean): true if code has issues that must be fixed, false if code is correct",
        "- `reasoning` (string): EXACTLY 2-4 sentences explaining your decision (NO MORE)",
        "",
        "**Conditional Field:**",
        "- `revised_code` (string): ONLY if needs_revision=true, provide targeted fixes using SEARCH/REPLACE format",
        "",
        "🚫 **If needs_revision=false (code is correct):**",
        "- DO NOT provide revised_code (must be null/omitted)",
        "- Original code will be used as-is",
        "- This prevents accidental modifications to working code",
        "",
        "✅ **If needs_revision=true (code has issues):**",
        "- MUST provide revised_code using SEARCH/REPLACE diff format",
        "- Use <<<<<<< SEARCH / ======= / >>>>>>> REPLACE blocks for each fix",
        "- SEARCH block must match original code EXACTLY (character-by-character, same indentation)",
        "- Only include the specific buggy lines that need fixing",
        "- Can provide multiple SEARCH/REPLACE blocks for different issues",
        "- Preserve the solution approach and model architecture",
        "- Fix only the specific issues identified (metric mismatch, data leakage, API errors)",
        "- DO NOT change model architecture, data split method, or metric calculation (unless they are buggy)",
        "",
        "**Reasoning Field Guidelines:**",
        "⚠️ STRICT LENGTH LIMIT: Write EXACTLY 2-4 sentences. Be concise.",
        "Cover: (1) what issues found, (2) why they matter, (3) what will be fixed.",
        "DO NOT write detailed analysis, step-by-step checks, or comprehensive explanations.",
        "",
        "**Why this format matters:**",
        "The JSON schema format ensures that code is ONLY modified when necessary.",
        "When needs_revision=false, it's impossible to accidentally change working code.",
        "⚠️ reasoning MUST be 2-4 sentences only. Do NOT write long analysis or enumerate checks."
    ]
